---
name: "Check build"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check_build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        system:
          - "x86_64-linux"
          - "aarch64-linux"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
            extra-sandbox-paths = /usr/bin
      - name: "Build docker"
        run: nix build .#packages.${{ matrix.system }}.iglu-builder-docker

