---
name: "Check nix formatting"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Check nix stuff"
        run: nix shell github:iglu-sh/flake#flakecheck --command flakecheck

